Update `target_*` function to warn and change `isos` to lower-case in `region_isos`
2DegreesInvesting/r2dii.analysis pull request #414
Opened 2022-05-13 14:18 UTC by julie-vienne

In case the input `region_isos` has upper-cases in `isos`, the `target_market_share` and `target_sda` function will call a function to change the upper-cases to lower-cases and will issue a warning to the user. If this is not done, the joining of `region_isos` outputs 0 rows. 

Closes 398.

2022-05-13 16:12 UTC, julie-vienne commented
@jdhoffa so far, I've only created a test for target_market_share to make sure the function change_to_lowercase_and_warn updates and warns as it's supposed to. Do you think such a test is also necessary in target_sda as this function is also called there?

2022-05-16 07:55 UTC, jdhoffa commented
> @jdhoffa so far, I've only created a test for target_market_share to make sure the function change_to_lowercase_and_warn updates and warns as it's supposed to. Do you think such a test is also necessary in target_sda as this function is also called there?

Yes, I would say test both. Maybe this is a good time to elaborate a bit: 
The tests you write in the `testthat` folder are called "unit tests". A "unit test" tests one unit of the code, defined as "an exported function of the R package". So the goal should be: Test the final behavior of the exported function, in a way that is invariant to how it is actually implemented. (The reason this is desired, is so that you are free to refactor the code sometime down the road). 

In regards to the above, the function you wrote `change_to_lowercase_and_warn` is just one possible way of implementing the behavior, but if you ever wanted to refactor the code, and remove that function, you would want to do so in such a way that you're sure that the behavior is preserved in both `target_market_share` and `target_sda`. The only way to be sure of that is to have tested both of the functions explicitly

2022-05-16 07:58 UTC, jdhoffa requested changes
LGTM, only change I would make is add the test also to `target_sda`

2022-05-16 13:46 UTC, jdhoffa approved these changes
lgtm

2022-05-16 13:46 UTC, merged